CREATE TABLE click_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_id BIGINT NOT NULL,
    ip_address VARCHAR(45),
    user_agent TEXT,
    referer TEXT,
    device_type VARCHAR(50),
    browser VARCHAR(100),
    os VARCHAR(100),
    country VARCHAR(100),
    city VARCHAR(100),
    clicked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (url_id) REFERENCES urls(id)
);

CREATE INDEX idx_url_id ON click_events (url_id);
CREATE INDEX idx_clicked_at ON click_events (clicked_at);
CREATE INDEX idx_url_clicked ON click_events (url_id, clicked_at);
