export const CREATE_URL_FORM_TEXT = {
    destinationUrl: "URL đích",
    destinationPlaceholder: "https://tenmien-dich.com/duong-dan",
    advancedOptions: "Tùy chọn nâng cao",
    hideAdvancedOptions: "Ẩn tùy chọn nâng cao",
    customAlias: "Bí danh",
    customAliasPlaceholder: "bi-danh",
    optional: "Không bắt buộc",
    password: "Mật khẩu",
    passwordPlaceholder: "••••••••",
    shortening: "Đang rút gọn...",
    shortenUrl: "Rút gọn URL",
} as const;

export const EDIT_URL_FORM_TEXT = {
    title: "Chỉnh sửa URL",
    description: "Cập nhật URL đích, bí danh, mật khẩu và thời hạn cho liên kết rút gọn.",
    originalUrl: "URL gốc",
    originalUrlPlaceholder: "https://example.com/trang",
    customAlias: "Bí danh",
    customAliasPlaceholder: "bi-danh",
    customAliasHint: "Tối đa 10 ký tự.",
    password: "Mật khẩu",
    passwordPlaceholder: "Để trống để xóa mật khẩu",
    passwordHint: "Đặt mật khẩu để bảo vệ truy cập. Để trống nếu muốn xóa mật khẩu.",
    expiresAt: "Ngày hết hạn",
    expiresAtHint: "Để trống nếu không đặt thời hạn.",
    cancel: "Hủy",
    saving: "Đang lưu...",
    saveChanges: "Lưu thay đổi",
    invalidExpiration: "Định dạng ngày hết hạn không hợp lệ.",
    validUrlMessage: "URL không hợp lệ",
    aliasMaxLengthMessage: "Bí danh tối đa 10 ký tự",
} as const;
